BEGIN;

SET search_path TO javaprak, public;

DROP TABLE IF EXISTS "Отклик" CASCADE;
DROP TABLE IF EXISTS "Резюме_Опыт" CASCADE;
DROP TABLE IF EXISTS "Резюме_Образование" CASCADE;
DROP TABLE IF EXISTS "Вакансия" CASCADE;
DROP TABLE IF EXISTS "Опыт_работы" CASCADE;
DROP TABLE IF EXISTS "Образование" CASCADE;
DROP TABLE IF EXISTS "Резюме" CASCADE;
DROP TABLE IF EXISTS "Компания" CASCADE;
DROP TABLE IF EXISTS "Соискатель" CASCADE;
DROP TABLE IF EXISTS "Должность" CASCADE;
DROP TABLE IF EXISTS "Уровень_образования" CASCADE;

CREATE TABLE "Уровень_образования" (
    "ID_уровня" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "Название" TEXT NOT NULL,
    PRIMARY KEY ("ID_уровня"),
    CONSTRAINT "uk_уровень_образования_название" UNIQUE ("Название")
);

CREATE TABLE "Должность" (
    "ID_должности" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "Название" TEXT NOT NULL,
    PRIMARY KEY ("ID_должности"),
    CONSTRAINT "uk_должность_название" UNIQUE ("Название")
);

CREATE TABLE "Соискатель" (
    "ID_соискателя" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "ФИО" TEXT NOT NULL,
    "Контактная_информация" TEXT NOT NULL,
    "Дата_рождения" DATE NOT NULL,
    "Домашний_адрес" TEXT NOT NULL,
    "Статус" BOOLEAN NOT NULL,
    PRIMARY KEY ("ID_соискателя")
);

CREATE TABLE "Компания" (
    "ID_компании" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "Название" TEXT NOT NULL,
    "Контактная_информация" TEXT NOT NULL,
    PRIMARY KEY ("ID_компании"),
    CONSTRAINT "uk_компания_название" UNIQUE ("Название")
);

CREATE TABLE "Резюме" (
    "ID_резюме" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "Соискатель" BIGINT NOT NULL,
    "ID_должности" BIGINT NOT NULL,
    "Желаемая_зарплата_мин" BIGINT NOT NULL,
    "Актуально" BOOLEAN NOT NULL,
    PRIMARY KEY ("ID_резюме"),
    CONSTRAINT "fk_резюме_соискатель"
        FOREIGN KEY ("Соискатель") REFERENCES "Соискатель"("ID_соискателя")
        ON DELETE CASCADE,
    CONSTRAINT "fk_резюме_должность"
        FOREIGN KEY ("ID_должности") REFERENCES "Должность"("ID_должности"),
    CONSTRAINT "chk_резюме_желаемая_зарплата_мин"
        CHECK ("Желаемая_зарплата_мин" >= 0)
);

CREATE TABLE "Образование" (
    "ID_образования" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "Уровень" BIGINT NOT NULL,
    "Место_учебы" TEXT NOT NULL,
    "Направление" TEXT NOT NULL,
    "Дата_начала" DATE NOT NULL,
    "Дата_окончания" DATE,
    PRIMARY KEY ("ID_образования"),
    CONSTRAINT "fk_образование_уровень"
        FOREIGN KEY ("Уровень") REFERENCES "Уровень_образования"("ID_уровня"),
    CONSTRAINT "chk_образование_даты"
        CHECK ("Дата_окончания" IS NULL OR "Дата_окончания" >= "Дата_начала")
);

CREATE TABLE "Опыт_работы" (
    "ID_опыта" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "Компания" TEXT NOT NULL,
    "ID_должности" BIGINT NOT NULL,
    "Дата_начала" DATE NOT NULL,
    "Дата_окончания" DATE,
    "Зарплата" BIGINT NOT NULL,
    PRIMARY KEY ("ID_опыта"),
    CONSTRAINT "fk_опыт_должность"
        FOREIGN KEY ("ID_должности") REFERENCES "Должность"("ID_должности"),
    CONSTRAINT "chk_опыт_зарплата"
        CHECK ("Зарплата" >= 0),
    CONSTRAINT "chk_опыт_даты"
        CHECK ("Дата_окончания" IS NULL OR "Дата_окончания" >= "Дата_начала")
);

CREATE TABLE "Вакансия" (
    "ID_вакансии" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "ID_компании" BIGINT NOT NULL,
    "ID_должности" BIGINT NOT NULL,
    "Зарплата" BIGINT NOT NULL,
    "Мин_стаж_месяцев" BIGINT NOT NULL,
    "Мин_уровень_образования" BIGINT NOT NULL,
    PRIMARY KEY ("ID_вакансии"),
    CONSTRAINT "fk_вакансия_компания"
        FOREIGN KEY ("ID_компании") REFERENCES "Компания"("ID_компании")
        ON DELETE CASCADE,
    CONSTRAINT "fk_вакансия_должность"
        FOREIGN KEY ("ID_должности") REFERENCES "Должность"("ID_должности"),
    CONSTRAINT "fk_вакансия_уровень"
        FOREIGN KEY ("Мин_уровень_образования") REFERENCES "Уровень_образования"("ID_уровня"),
    CONSTRAINT "chk_вакансия_зарплата"
        CHECK ("Зарплата" >= 0),
    CONSTRAINT "chk_вакансия_мин_стаж"
        CHECK ("Мин_стаж_месяцев" >= 0)
);

CREATE TABLE "Резюме_Образование" (
    "ID_резюме" BIGINT NOT NULL,
    "ID_образования" BIGINT NOT NULL,
    PRIMARY KEY ("ID_резюме", "ID_образования"),
    CONSTRAINT "fk_резюме_образование_резюме"
        FOREIGN KEY ("ID_резюме") REFERENCES "Резюме"("ID_резюме")
        ON DELETE CASCADE,
    CONSTRAINT "fk_резюме_образование_образование"
        FOREIGN KEY ("ID_образования") REFERENCES "Образование"("ID_образования")
        ON DELETE CASCADE
);

CREATE TABLE "Резюме_Опыт" (
    "ID_резюме" BIGINT NOT NULL,
    "ID_опыта" BIGINT NOT NULL,
    PRIMARY KEY ("ID_резюме", "ID_опыта"),
    CONSTRAINT "fk_резюме_опыт_резюме"
        FOREIGN KEY ("ID_резюме") REFERENCES "Резюме"("ID_резюме")
        ON DELETE CASCADE,
    CONSTRAINT "fk_резюме_опыт_опыт"
        FOREIGN KEY ("ID_опыта") REFERENCES "Опыт_работы"("ID_опыта")
        ON DELETE CASCADE
);

CREATE TABLE "Отклик" (
    "ID_отклика" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "ID_резюме" BIGINT NOT NULL,
    "ID_вакансии" BIGINT NOT NULL,
    "Статус" VARCHAR(32) NOT NULL,
    "Дата" DATE NOT NULL,
    PRIMARY KEY ("ID_отклика"),
    CONSTRAINT "fk_отклик_резюме"
        FOREIGN KEY ("ID_резюме") REFERENCES "Резюме"("ID_резюме")
        ON DELETE CASCADE,
    CONSTRAINT "fk_отклик_вакансия"
        FOREIGN KEY ("ID_вакансии") REFERENCES "Вакансия"("ID_вакансии")
        ON DELETE CASCADE,
    CONSTRAINT "chk_отклик_статус"
        CHECK ("Статус" IN ('recommended','sent','rejected','accepted'))
);

COMMIT;