BEGIN;

DROP TABLE IF EXISTS "Отклик" CASCADE;
DROP TABLE IF EXISTS "Резюме_Опыт" CASCADE;
DROP TABLE IF EXISTS "Резюме_Образование" CASCADE;
DROP TABLE IF EXISTS "Вакансия" CASCADE;
DROP TABLE IF EXISTS "Опыт_работы" CASCADE;
DROP TABLE IF EXISTS "Образование" CASCADE;
DROP TABLE IF EXISTS "Резюме" CASCADE;
DROP TABLE IF EXISTS "Компания" CASCADE;
DROP TABLE IF EXISTS "Соискатель" CASCADE;
DROP TABLE IF EXISTS "Должность" CASCADE;
DROP TABLE IF EXISTS "Уровень_образования" CASCADE;

COMMIT;